### ISSUE TITLE
Multiplier values, Divider only accepts integer values

### ISSUE THREAD

**Issue by cofhal** [aekhv/vfdmod#1]
My VDF is a Fuling model DZB280, to adjust the frequency I must divide the RPM by 2.4, but the program only allows integers, it would be possible to replace the Multiplier, Divider values with a floating type variable.

**Comment by aekhv** [comment]
Yep, only integers value are accepted. Use both (divider and multiplier) to reach float coefficient. For example, if your RPM value should be divided by 2.4 (or multiplied to 1 / 2.4):
```
Multiplier=10
Divider=24
```
